/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-Apache-2.0
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use std::path::PathBuf;

use ::tonic_client_wrapper::codegen;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let autogenerated_rust_output_directory = out_dir.clone();
    // The reflection path is part of the output directory (which might be debug or release),
    // so that different builds get a different binary file and concurrent builds don't collide
    let reflection = out_dir.join("rms.bin");

    tonic_prost_build::configure()
        .file_descriptor_set_path(reflection)
        .type_attribute(
            "rack_manager.PowerOperation",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.RackPowerOperation",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ReturnCode",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.FirmwareUpdateError",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NodeType",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.SwitchFirmwareComponentType",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpgradeStage",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NewNodeInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NodeSet",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NodeUpdateInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NodeInventoryInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NodeDeviceInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.DeviceInventoryInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.FirmwareInventoryInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UsernamePassword",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.Credentials",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .enum_attribute(
            "rack_manager.Credentials.auth",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.BmcEndpoint",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NetworkInterface",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.HostEndpoint",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.Metadata",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.PowerOnOrderItem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.CompletionCheck",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NodeFirmwareInventory",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NodeUpdateResult",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.SetPowerStateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.SetPowerStateResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetPowerStateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetPowerStateResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.SequenceRackPowerRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.SequenceRackPowerResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetAllInventoryRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetAllInventoryResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.AddNodeRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.AddNodeResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateNodeRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateNodeResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.RemoveNodeRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.RemoveNodeResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetRackPowerOnSequenceRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetRackPowerOnSequenceResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.SetRackPowerOnSequenceRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.SetRackPowerOnSequenceResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ListRacksRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ListRacksResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetNodeDeviceInfoRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetNodeDeviceInfoResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetDeviceInfoByNodeTypeRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetDeviceInfoByNodeTypeResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetDeviceInfoByDeviceListRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetDeviceInfoByDeviceListResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetNodeFirmwareInventoryRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetNodeFirmwareInventoryResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateNodeFirmwareRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateNodeFirmwareResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateFirmwareByNodeTypeRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetRackFirmwareInventoryRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetRackFirmwareInventoryResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ConfigureScaleUpFabricManagerRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ConfigureScaleUpFabricManagerResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ScaleUpFabricServiceStatusEntry",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetScaleUpFabricServicesStatusRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetScaleUpFabricServicesStatusResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetScaleUpFabricStateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetScaleUpFabricStateResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.FetchSwitchSystemImageRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.FetchSwitchSystemImageResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.InstallSwitchSystemImageRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.InstallSwitchSystemImageResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ListSwitchSystemImagesRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ListSwitchSystemImagesResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.EnableScaleUpFabricTelemetryInterfaceRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.EnableScaleUpFabricTelemetryInterfaceResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ListFirmwareOnSwitchCommand",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.ListFirmwareOnSwitchResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.PushFirmwareToSwitchCommand",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.PushFirmwareToSwitchResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpgradeFirmwareOnSwitchCommand",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpgradeFirmwareOnSwitchResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.PollJobStatusCommand",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.PollJobStatusResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.FirmwareJobState",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.FirmwareTarget",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.FirmwareTargetList",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.NodeFirmwareJobInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateFirmwareByNodeTypeAsyncResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateFirmwareByDeviceListRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateFirmwareByDeviceListResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.SwitchSystemImageUpdateJobInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateSwitchSystemImageRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateSwitchSystemImageResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetFirmwareJobStatusRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetFirmwareJobStatusResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetSwitchSystemImageJobStatusRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.GetSwitchSystemImageJobStatusResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateSwitchSystemPasswordRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "rack_manager.UpdateSwitchSystemPasswordResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .include_file("prost_common.rs")
        .build_server(false)
        .build_client(true)
        .protoc_arg("--experimental_allow_proto3_optional")
        .out_dir(autogenerated_rust_output_directory)
        .compile_protos(&["proto/rack_manager.proto"], &["proto"])
        .unwrap();

    // enable the code generator for the rack manager proto
    let rms_client_wrapper = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "RackManagerApiClient".to_string(),
        inner_rpc_client_type: "crate::RackManagerClientT".to_string(),
        proto_files: vec!["proto/rack_manager.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        extern_paths: vec![],
        generated_types_path_within_crate: "protos".to_string(),
    })?;
    rms_client_wrapper.write_rpc_client_wrapper(out_dir.join("rack_manager_client.rs"))?;
    rms_client_wrapper
        .write_rpc_convenience_converters(out_dir.join("rack_manager_converters.rs"))?;

    Ok(())
}
