/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-Apache-2.0
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use std::path::PathBuf;

use ::tonic_client_wrapper::codegen;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let autogenerated_rust_output_directory = out_dir.clone();
    // The reflection path is part of the output directory (which might be debug or release),
    // so that different builds get a different binary file and concurrent builds don't collide
    let reflection = out_dir.join("rms.bin");

    tonic_prost_build::configure()
        .file_descriptor_set_path(reflection)
        // Leading dot makes this a prefix match in prost-build's PathMap, covering every message
        // and enum whose FQN starts with ".rack_manager" (i.e. the entire package).
        .type_attribute(
            ".rack_manager",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .include_file("prost_common.rs")
        .build_server(false)
        .build_client(true)
        .protoc_arg("--experimental_allow_proto3_optional")
        .out_dir(autogenerated_rust_output_directory)
        .compile_protos(&["proto/rack_manager.proto"], &["proto"])
        .unwrap();

    // enable the code generator for the rack manager proto
    let rms_client_wrapper = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "RackManagerApiClient".to_string(),
        inner_rpc_client_type: "crate::RackManagerClientT".to_string(),
        proto_files: vec!["proto/rack_manager.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        extern_paths: vec![],
        generated_types_path_within_crate: "protos".to_string(),
    })?;
    rms_client_wrapper.write_rpc_client_wrapper(out_dir.join("rack_manager_client.rs"))?;
    rms_client_wrapper
        .write_rpc_convenience_converters(out_dir.join("rack_manager_converters.rs"))?;

    Ok(())
}
